### ISSUE TITLE
When running a wxmx file from hard drive, the file on hard drive gets overwritten immediately

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1168]
Is this something new?  I seem to remember that this was not the case.  After fixing errors, I would need to save the wxmx file.

Now, if a beta version of WxMaxima produces errors it overwrites the errors in my test file on the hard drive.  I have lost my original test file.

It should not overwrite my original file unless I do a save.

Richard

**Comment by gunterkoenigsmann** [comment]
Arrgh! That sounds bad. And I think I found the error: I replaced the "autosave every n minutes" option by an "autosave as temp file" one - but didn't set the latter option depending the "autosave every n minutes" having been set in the prious wxMaxima version. Sorry for that!

**Comment by richardgobeli** [comment]
![image](https://user-images.githubusercontent.com/31253976/68064653-7233f580-fcec-11e9-8d80-5c68e4de1c79.png)
I was waiting about 2 minutes and the WxMaxima just disappeared.  I guess it crashed.
I started it again and loaded a small wxmx file.   The screen does not update correctly.  Some parts are blank and the input brackets on the left are not there.   The window just crashed again.

If I click the screen with the mouse it refreshes, but it is blank again if I scroll down.  This behavior is very weird.

I am not sure if this version is with today's changes.  It was 7:30 pm CDT time when I downloaded.
It has data 11-02-2019.

**Comment by richardgobeli** [comment]
For me, the original file is still getting overwritten.
 
![image](https://user-images.githubusercontent.com/31253976/68078561-42492880-fda6-11e9-9150-b29e9ae19882.png)
When scrolling the display seems to be limited to only what was shown on the first screen.  It never seems to display any part of the file below the first screen height.  Here I have made my window smaller to see this effect.
first screen.
![image](https://user-images.githubusercontent.com/31253976/68078577-a5d35600-fda6-11e9-9723-413c54409597.png)
scrolled half way up and bottom of screen stayed blank, until moving mouse cause screen to rewrite like this.  This is still the first screen even though my scroll bar isn't at the top.
![image](https://user-images.githubusercontent.com/31253976/68078584-ec28b500-fda6-11e9-8e2f-03909b742d18.png)

**Comment by gunterkoenigsmann** [comment]
Ok... ...the crashes should be resolved now. And there should again be debug messages in the debug sidebar telling why wxMaxima takes a wrong decision so with your help we can debug this.
About the display issue I am kind of unsure where it could come from, though...

**Comment by richardgobeli** [comment]
![image](https://user-images.githubusercontent.com/31253976/68174060-588beb80-ff42-11e9-8120-670ebe77f83b.png)
The temp file still gets written to the original, when WxMaxima is closed.  It does not ask if you want to save,  not save, or cancel.
Also I see the temp files don't get deleted after the program is stopped.

**Comment by richardgobeli** [comment]
This version works for the screen rewriting!  
The program still does not ask, when WxMaxima is closed, if you want to save the current data or not save.  It just goes and writes over the original file.  It does ask the question of saving if a new file will be opened.
![image](https://user-images.githubusercontent.com/31253976/68271602-ad089700-0026-11ea-999e-571097055612.png)

**Comment by gunterkoenigsmann** [comment]
This set of debug messages seems to indicate that in the config dialogue the "options/don't save the worksheet automatically" checkbox isn't checked.

Do you have a better label I can give to  this checkbox?

**Comment by richardgobeli** [comment]
Yes, the box Don't save automatically was not checked.
It is working better now.  It will now ask even on closing the app.

**Comment by richardgobeli** [comment]
![image](https://user-images.githubusercontent.com/31253976/68533689-8336c500-02f1-11ea-8143-b982a7e41936.png)
This is a lot easier to go thru demos with the arrow button.  This also would be a great asset for the debugger, because it has all of different complex step commands.

**Comment by richardgobeli** [comment]
I see you named it "save the worksheet automatically" if checked.
This name is easier to understand.

**Comment by gunterkoenigsmann** [comment]
I was never sure how to name that button and it got misinterpreted by at least two independent beings => I had to change this button.
