### ISSUE TITLE
Tests: Errors from unicode characters 

### ISSUE THREAD

**Issue by badshah400** [wxMaxima-developers/wxmaxima#1699]
When building wxMaxima for openSUSE Tumbleweed (relevant library versions listed below), we also run the tests using `ctest`. However, recently this has been recently failing with the following errors from tests that use unicode characters (this used to work fine, even with wxMaxima 22.04.0, so it is likely some incompatibility with an underlying library that has been updated in the meanwhile may be the issue).

```
[  363s] + /usr/bin/ctest --output-on-failure --force-new-ctest-process -j8
[  363s] Test project /home/abuild/rpmbuild/BUILD/wxmaxima-Version-22.04.0/build
[  363s]         Start   1: runMaxima
[  363s]         Start   2: runMaxima-over-network
[  363s]         Start   3: wxmaxima_batch_emptyFile
[  363s]         Start   4: wxmaxima_performance
[  363s]         Start   5: wxmaxima_batch_textcell
[  363s]         Start   6: wxmaxima_batch_foreign_characters
[  363s]         Start   7: wxmaxima_version_string
[  363s]         Start   8: wxmaxima_version_returncode
[  363s]   1/103 Test   #1: runMaxima ...................................   Passed    0.03 sec
[  363s]         Start   9: wxmaxima_help
[  363s]   2/103 Test   #2: runMaxima-over-network ......................   Passed    0.04 sec
[  363s]         Start  10: all_celltypes
[  363s]   3/103 Test   #9: wxmaxima_help ...............................   Passed    0.09 sec
[  363s]         Start  11: simpleInput
[  363s]   4/103 Test   #8: wxmaxima_version_returncode .................   Passed    0.10 sec
[  363s]         Start  12: rememberingAnswers
[  363s]   5/103 Test   #7: wxmaxima_version_string .....................   Passed    0.12 sec
[  363s]         Start  13: absCells_cmdline
[  363s]   6/103 Test  #13: absCells_cmdline ............................   Passed    0.13 sec
[  363s]         Start  14: absCells
[  366s]   7/103 Test   #4: wxmaxima_performance ........................***Exception: SegFault  3.31 sec
[  366s] 11:25:43 PM: wxMaxima version 22.04.0
[  366s] 11:25:43 PM: OS: Linux 5.18.2-1-default x86_64 Version 5.18
[  366s] 11:25:43 PM: wxWidgets 3.1.5
[  366s] 11:25:43 PM: wxWidgets is using GTK 3
[  366s] 11:25:43 PM: Translations are read from /home/abuild/rpmbuild/BUILD/wxmaxima-Version-22.04.0/build/share/locale.
[  366s] 11:25:43 PM: Reading the config from the default location.
[  366s] 11:25:43 PM: Reading the glyph renderability cache
[  366s] 11:25:43 PM: XML parsing error: 'no element found' at line 1
[  366s] 11:25:43 PM: XML parsing error: 'no element found' at line 1
[  366s] 11:25:43 PM: Reading the glyph renderability cache
[  366s] 11:25:43 PM: XML parsing error: 'no element found' at line 1
[  366s] 11:25:43 PM: XML parsing error: 'no element found' at line 1
[  366s] 11:25:43 PM: FontCache Raw Miss: 10.00pt  ---- "Arial" fam:70 enc:0
[  366s] 11:25:43 PM: FontCache Resolved: 10.00pt  ---- "Arial" fam:70 enc:43
[  366s] 11:25:43 PM: FontCache Raw Miss: 10.00pt  BI-- "Arial" fam:70 enc:0
[  366s] 11:25:43 PM: FontCache Resolved: 10.00pt  BI-- "Arial" fam:70 enc:43
[  366s] 11:25:43 PM: Char 'Î±' seems not to be displayed.
[  366s] 11:25:43 PM: Char 'Î±' looks identical to ''.
[  366s] 11:25:43 PM: Char 'Î²' seems not to be displayed.
[  366s] 11:25:43 PM: Char 'Î²' seems not to be displayed.
[  366s] 11:25:43 PM: Char 'Î³' looks identical to 'ïŠ™'.
[  366s] 11:25:43 PM: Char 'Î³' seems not to be displayed.
[  366s] 11:25:43 PM: Char 'Î´' seems not to be displayed.
[  366s] 11:25:43 PM: Char 'Î´' seems not to be displayed.
[  366s] 11:25:43 PM: Char 'Îµ' seems not to be displayed.
[  366s] 11:25:43 PM: Char 'Îµ' looks identical to 'ïŠ™'.
[  366s] 11:25:43 PM: Char 'Î¶' seems not to be displayed.
[  366s] 11:25:43 PM: Char 'Î¶' looks identical to 'ï€€'.
```

and on and on.

The following compilers/libraries are used during compilation:

* wxMaxima 22.04.0
* GCC 12.1
* wxWidgets 3.1.5
* Python 3.10
* GTK 3.24.34
* WebKITGTK 2.36.4

Full build log [attached here](https://github.com/wxMaxima-developers/wxmaxima/files/9154986/_log.zip).

Any suggestion as to what the issue may be due to would be much appreciated.

Thank you.

**Comment by gunterkoenigsmann** [comment]
The Unicode looks like a Red Herring to me: wxMaxima now tests what characters can be displayed and outputs debug messages about that. But I am not sure if that is what causes the test failure...

**Comment by badshah400** [comment]
At the end, ctest summarises the test status as thus:

```
[  394s] 51% tests passed, 50 tests failed out of 103
[  394s] 
[  394s] Total Test time (real) =  31.08 sec
[  394s] 
[  394s] The following tests FAILED:
[  394s] 	  3 - wxmaxima_batch_emptyFile (SEGFAULT)
[  394s] 	  4 - wxmaxima_performance (SEGFAULT)
[  394s] 	  5 - wxmaxima_batch_textcell (SEGFAULT)
[  394s] 	  6 - wxmaxima_batch_foreign_characters (SEGFAULT)
[  394s] 	 10 - all_celltypes (SEGFAULT)
[  394s] 	 11 - simpleInput (SEGFAULT)
[  394s] 	 12 - rememberingAnswers (SEGFAULT)
[  394s] 	 14 - absCells (SEGFAULT)
[  394s] 	 16 - diffCells (SEGFAULT)
[  394s] 	 19 - atCells (SEGFAULT)
[  394s] 	 22 - conjugateCells (SEGFAULT)
[  394s] 	 25 - exptCells (SEGFAULT)
[  394s] 	 29 - fracCells (SEGFAULT)
[  394s] 	 32 - intCells (SEGFAULT)
[  394s] 	 35 - intervals (SEGFAULT)
[  394s] 	 38 - functionCells (SEGFAULT)
[  394s] 	 39 - slideshowCells (SEGFAULT)
[  394s] 	 40 - imageCells (SEGFAULT)
[  394s] 	 43 - limitCells (SEGFAULT)
[  394s] 	 46 - matrixCells (SEGFAULT)
[  394s] 	 49 - parenthesisCells (SEGFAULT)
[  394s] 	 52 - listCells (SEGFAULT)
[  394s] 	 55 - setCells (SEGFAULT)
[  394s] 	 58 - sqrtCells (SEGFAULT)
[  394s] 	 61 - subCells (SEGFAULT)
[  394s] 	 64 - subsupCells (SEGFAULT)
[  394s] 	 67 - presubsupcells (SEGFAULT)
[  394s] 	 70 - sumCells (SEGFAULT)
[  394s] 	 73 - printf_simple (SEGFAULT)
[  394s] 	 76 - printf_equations (SEGFAULT)
[  394s] 	 79 - printf_continuationLines (SEGFAULT)
[  394s] 	 80 - weirdLabels (SEGFAULT)
[  394s] 	 81 - xmlQuote (SEGFAULT)
[  394s] 	 82 - formerCrashes (SEGFAULT)
[  394s] 	 83 - multiplication (SEGFAULT)
[  394s] 	 84 - nonsenseConstructs (SEGFAULT)
[  394s] 	 85 - lisp (SEGFAULT)
[  394s] 	 86 - boxes (SEGFAULT)
[  394s] 	 87 - unicode (SEGFAULT)
[  394s] 	 88 - unicode_specialchars (SEGFAULT)
[  394s] 	 89 - openMacFiles (SEGFAULT)
[  394s] 	 90 - openMacFiles2 (SEGFAULT)
[  394s] 	 91 - tutorial_10Minutes (SEGFAULT)
[  394s] 	 92 - comment_begin (SEGFAULT)
[  394s] 	 93 - threadtest (SEGFAULT)
[  394s] 	 94 - autosave (SEGFAULT)
[  394s] 	 95 - noautosave (SEGFAULT)
[  394s] 	 96 - config_from_19.11 (SEGFAULT)
[  394s] 	100 - ipc_copypaste1 (SEGFAULT)
[  394s] 	101 - ipc_copypaste_all-celltypes (SEGFAULT)
```

**Comment by badshah400** [comment]
Sorry, forgot to mention that we use maxima 5.46.0 with SBCL as the lisp backend.

**Comment by gunterkoenigsmann** [comment]
I believe this should be resolved in the git main trunk...

**Comment by badshah400** [comment]
Thanks a lot for the quick fix. Any specific commit I could cherrypick to apply against 22.05 and get our openSUSE builds going again?

**Comment by badshah400** [comment]
Sorry, just checked and still a problem with version 22.09.0

**Comment by gunterkoenigsmann** [comment]
Might it be that your wcWidgets was Compiled without Unicode support?

**Comment by gunterkoenigsmann** [comment]
Wait: This is a segfault.

Do you have gdb installed?

If yes: can you give me the output of the gdb command

````
backtrace
````
after the segfault?

**Comment by gunterkoenigsmann** [comment]
If wcMaxima is compiled with debug symbols gdb should in that case tell us the exact line number of the crash.

**Comment by gunterkoenigsmann** [comment]
If wxMaxima is compiled with debug symbols gdb should in that case tell us the exact line number of the crash.

**Comment by badshah400** [comment]
@gunterkoenigsmann Sorry, I shall get back to this next week and try to see if I can run gdb from inside the spec file (I see the errors when running the tests while building RPMs for openSUSE).

**Comment by gunterkoenigsmann** [comment]
What might work is (if libSegFault is to be found in /lib):

````
export SEGFAULT_SIGNALS="abrt segv" 
export LD_PRELOAD=/lib/libSegFault.so 
export CTEST_OUTPUT_ON_FAILURE=1
xvfb-run -a ctest
````
In order to get a backtrace with function names and line numbers one might need to run cmake with the switch `-DCMAKE_BUILD_TYPE=debug` for configuring the project.

@badshah400 If the trick with the library doesn't work: The tests are described in `test/CMakeLists.txt` and most tests consist of a very simple command-line. The only pitfall might be that the path to the wxMaxima binary is filled in by cmake on testing.

**Comment by gunterkoenigsmann** [comment]
Perhaps the xvfb-run isn't a especially good idea: It suppresses opening windows for the test, but often causes bugs in xvfb-run to show...

**Comment by badshah400** [comment]
Sorry, I totally lost track of this. Not able to succeed with the segfault library trick, I tried running each test manually (i.e. without ctest). As it turns out, the tests do not segfault but instead get dead-locked; the ctest timeout causes them to be aborted. The `wxmaxima_performance` (number 4 from the list of failed tests, see) does this when run manually:

```
[   61s] + /usr/bin/wxmaxima --logtostderr --pipe --batch performance.wxm
[   61s] Fontconfig error: No writable cache directories
[   61s] Fontconfig error: No writable cache directories
[   61s] Fontconfig error: No writable cache directories
[   61s] Fontconfig error: No writable cache directories
[   62s] 05:36:57 PM: wxMaxima version 22.09.0
[   62s] 05:36:57 PM: OS: Linux 6.0.7-1-default x86_64 Version 6.0
[   62s] 05:36:57 PM: wxWidgets 3.2.1
[   62s] 05:36:57 PM: wxWidgets is using GTK 3
[   62s] 05:36:57 PM: Translations are read from /usr/share/locale.
[   62s] 05:36:57 PM: Reading the config from the default location.
[   62s] 05:36:58 PM: Gnuplot found at: /usr/bin/gnuplot
[   62s] 05:36:58 PM: LANG=C
[   62s] 05:36:58 PM: Worksheet got the mouse focus
[   62s] 05:36:58 PM: Not connected to Maxima
[   62s] 05:36:58 PM: Welcome to wxMaxima
[   62s] 05:36:58 PM: Worksheet got the mouse focus
[  314s]
```

Just freezes there forever. Ditto for all the other tests.

Thanks for your suggestions, and please accept my apologies for the delay in getting back to this.

**Comment by gunterkoenigsmann** [comment]
Starting with the "314 Seconds" something seems to be severely wrong. In the meantime I have re-written many parts that might be part of this problem => it might be possible that the problem has already been resolved by accident now.

**Comment by badshah400** [comment]
Thanks, I will re-try enabling the tests for our packages for the next tagged version.

**Comment by gunterkoenigsmann** [comment]
Should resolve by now.
